-- mysql -u root 
-- 1234
SET NAMES utf8
DEFAULT CHARSET=utf8


DROP datalyze;
CREATE DATABASE datalyze;
USE datalyze;

DROP TABLE F03_MUN_2015;
DROP TABLE F05_1_MUN_2015;
DROP TABLE F06_1_MUN_2015;
DROP TABLE F09_MUN_2015;
DROP TABLE F10_MUN_2015;


create table if not exists F03_MUN_2015(
TIPO_ELECCION INT(10),
ANIO INT(5),
MES INT(10),
COD_CAND INT(10),
SIGLAS_CAND VARCHAR(200),
DENOM_CAND VARCHAR(200),
COD_NPROV INT(10),
COD_NAUT INT(10),
COD_NNAC INT(10),
PRIMARY KEY (COD_CAND)
);


LOAD DATA INFILE 'C:/hugo_documentos/otros/github/python-scripts/data_analisis_electoral_data/recursos_input/F03_MUN_2015.csv' 
INTO TABLE F03_MUN_2015
CHARACTER SET 'utf8'
COLUMNS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SELECT * FROM F03_MUN_2015 LIMIT 5;

create table if not exists F05_1_MUN_2015(
TIPO_ELECCION  INT(10),
ANIO           INT(10),
MES            INT(10),
VUELTA         INT(10),
COD_CCAA       INT(10),
COD_PROV       INT(10),
COD_MUN        INT(10),
DISTRITO       INT(10),
MUNICIPIO      VARCHAR(50),
COD_DIST_ELEC  INT(10),
COD_PART_JUD   INT(10),
COD_DIP_PROV   INT(10),
COD_COM        INT(10),
POBLACION_DER  INT(10),
N_MESAS        INT(10),
CENSO          INT(10),
CENSO_ESCR     INT(10),
CENSO_CERE     INT(10),
VOTOS_CERE     INT(10),
VOTOS_1AVANCE  INT(10),
VOTOS_2AVANCE  INT(10),
VOTOS_BLANCO   INT(10),
VOTOS_NULOS    INT(10),
VOTOS_CAND     INT(10),
ESCANIOS        INT(10),
VOTOS_REFR_SI  INT(10),
VOTOS_REFR_NO  INT(10),
DATOS_OFIC     INT(10),
PRIMARY KEY (COD_CCAA, COD_PROV, COD_MUN,DISTRITO)
);

 
LOAD DATA INFILE 'C:/hugo_documentos/otros/github/python-scripts/data_analisis_electoral_data/recursos_input/F05_1_MUN_2015.csv' 
INTO TABLE F05_1_MUN_2015
CHARACTER SET 'utf8'
COLUMNS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SELECT * FROM F05_1_MUN_2015 LIMIT 5;

create table if not exists F06_1_MUN_2015(
TIPO_ELECCION  INT(10),
ANIO           INT(10),
MES            INT(10),
VUELTA         INT(10),
COD_PROV       INT(10),
COD_MUN        INT(10),
DIST_ELEC      INT(10),
COD_CAND       INT(10),
VOTOS_CAND     INT(10),
CAND_OBTENIDOS INT(10),
PRIMARY KEY (COD_PROV, COD_MUN,DIST_ELEC,COD_CAND)
);

LOAD DATA INFILE 'C:/hugo_documentos/otros/github/python-scripts/data_analisis_electoral_data/recursos_input/F06_1_MUN_2015.csv' 
INTO TABLE F06_1_MUN_2015
CHARACTER SET 'utf8'
COLUMNS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SELECT * FROM F06_1_MUN_2015 LIMIT 5;

create table if not exists F09_MUN_2015(
TIPO_ELECCION     INT(10),
ANIO              INT(10),
MES               INT(10),
VUELTA            INT(10),
COD_CCAA          INT(10),
COD_PROV          INT(10),
COD_MUN           INT(10),
DISTRITO          INT(10),
SECCION           INT(10),
MESA              VARCHAR(10),
CENSO             INT(10),
CENSO_ESCR_CERA   INT(10),
CENSO_CERE_ESCR   INT(10),
VOTOS_CERE        INT(10),
VOTOS_1AVANCE     INT(10),
VOTOS_2AVANCE     INT(10),
VOTOS_BLANCO      INT(10),
VOTOS_NULOS       INT(10),
VOTOS_CAND        INT(10),
REFR_SI           INT(10),
REFR_NO           INT(10),
DATOS_OFICIALES   VARCHAR(10),
PRIMARY KEY (COD_CCAA,COD_PROV, COD_MUN,DISTRITO,SECCION,MESA)
);

LOAD DATA INFILE 'C:/hugo_documentos/otros/github/python-scripts/data_analisis_electoral_data/recursos_input/F09_MUN_2015.csv' 
INTO TABLE F09_MUN_2015
CHARACTER SET 'utf8'
COLUMNS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SELECT * FROM F09_MUN_2015 LIMIT 5;

create table if not exists F10_MUN_2015(
TIPO_ELECCION INT(10),
ANIO          INT(10),
MES           INT(10),
VUELTA        INT(10),
COD_CCAA      INT(10),
COD_PROV      INT(10),
COD_MUN       INT(10),
DISTRITO      INT(10),
SECCION       INT(10),
MESA          VARCHAR(10),
COD_CAND      INT(10),
VOTOS_CAND    INT(10),
PRIMARY KEY (COD_CCAA,COD_PROV, COD_MUN,DISTRITO,SECCION,MESA,COD_CAND)
);

LOAD DATA INFILE 'C:/hugo_documentos/otros/github/python-scripts/data_analisis_electoral_data/recursos_input/F10_MUN_2015.csv' 
INTO TABLE F10_MUN_2015
CHARACTER SET 'utf8'
COLUMNS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SELECT * FROM F10_MUN_2015 LIMIT 5;